#######################react app.yaml file#################
env: standard
runtime: nodejs10
service: default

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
######### optional gae flex config (run from build folder) ########
# runtime: nodejs
# env: flex
#
# config optimized for demo for cost savings (not production)
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
# memory_gb: 0.5
# disk_size_gb: 10
########################## Gcloud commands in cloud sql terminal as follows

#gcloud config set project <project-id>
#mkdir <name of directory>
#gsutil rsync -r gs://iocsankari-bucket ./react-app
#cd <name of directory>
#gcloud app deploy

#https://iocsankari-react.el.r.appspot.com
